package com.example.guesstheplayerapp

object QuestionSource {

    const val CorrectAnswer = "correct_answers"
    const val Username = "username"


    fun guessPlayer() : List<clubs>{
        val guessplayer : List<clubs> = listOf(
            clubs(
                R.drawable.sporting,
                R.drawable.mutd,
                R.drawable.rm,
                R.drawable.juventus,
                R.drawable.mutd,
                0,
                "RONALDO",
                R.drawable.ronaldo
            ),
            clubs(
                R.drawable.fcb,
                R.drawable.paris,
                0,
                0,
                0,
                0,
                "MESSI",
                R.drawable.messi
            ),
            clubs(
                R.drawable.rosario,
                R.drawable.benfica,
                R.drawable.rm,
                R.drawable.mutd,
                R.drawable.paris,
                0,
                "DI MARIA",
                R.drawable.dimaria
            ),
            clubs(
                R.drawable.independiente,
                R.drawable.atm,
                R.drawable.mancity,
                R.drawable.fcb,
                0,
                0,
                "AGUERO",
                R.drawable.aguero
            ),
            clubs(
                R.drawable.metz,
                R.drawable.salzburg,
                R.drawable.southampton,
                R.drawable.lvp,
                0,
                0,
                "MANE",
                R.drawable.mane
            ),
            clubs(
                R.drawable.fcb,
                R.drawable.chelsea,
                R.drawable.roma,
                R.drawable.lazio,
               0,
                0,
                "PEDRO",
                R.drawable.pedro
            ),
            clubs(
                R.drawable.mutd,
                R.drawable.zaragoza,
                R.drawable.fcb,
                0,
                0,
                0,
                "PIQUE",
                R.drawable.pique
            ),
            clubs(
                R.drawable.genk,
                R.drawable.chelsea,
                R.drawable.bremen,
                R.drawable.wolfsburg,
                R.drawable.mancity,
                0,
                "DE BRUYNE",
                R.drawable.debruyne
            ),
            clubs(
                R.drawable.lyon,
                R.drawable.rm,
                0,
                0,
                0,
                0,
                "BENZEMA",
                R.drawable.benzema
            ),
            clubs(
                R.drawable.deltawarsaw,
                R.drawable.legia,
                R.drawable.prusk,
                R.drawable.kech,
                R.drawable.borrusia,
                R.drawable.bayern,
                "LEWANDOWSKI",
                R.drawable.lewa
            ),
            clubs(
                R.drawable.monaco,
                R.drawable.paris,
                0,
                0,
                0,
                0,
                "MBAPPE",
                R.drawable.mbappe
            ),
            clubs(
                R.drawable.salahclub1,
                R.drawable.basel,
                R.drawable.chelsea,
                R.drawable.fiorentina,
                R.drawable.roma,
                R.drawable.lvp,
                "SALAH",
                R.drawable.salah
            ),
            clubs(
                R.drawable.bryne,
                R.drawable.molde,
                R.drawable.salzburg,
                R.drawable.borrusia,
                R.drawable.mancity,
                0,
                "HAALAND",
                R.drawable.haaland
            ),
            clubs(
                R.drawable.nacional,
                R.drawable.groningen,
                R.drawable.ajax,
                R.drawable.lvp,
                R.drawable.fcb,
                R.drawable.atm,
                "SUAREZ",
                R.drawable.suarez
            ),
            clubs(
                R.drawable.santos,
                R.drawable.fcb,
                R.drawable.paris,
                0,
                0,
               0,
                "NEYMAR",
                R.drawable.neymar
            ),
            clubs(
                R.drawable.lvp,
                R.drawable.mancity,
                0,
                0,
                0,
                0,
                "STERLING",
                R.drawable.sterling
            ),
            clubs(
                R.drawable.hamburg,
                R.drawable.leverkusen,
                R.drawable.tottenham,
                0,
                0,
                0,
                "SON",
                R.drawable.son
            ),
            clubs(
                R.drawable.chelsea,
                R.drawable.vitesse,
                R.drawable.derby,
                R.drawable.chelsea,
                0,
                0,
                "MOUNT",
                R.drawable.mount
            ),
            clubs(
                R.drawable.boulogne,
                R.drawable.smcaen,
                R.drawable.leicester,
                R.drawable.chelsea,
                0,
                0,
                "KANTE",
                R.drawable.kante
            ),
            clubs(
                R.drawable.rm,
                R.drawable.borrusia,
                R.drawable.intermilan,
                R.drawable.paris,
                0,
                0,
                "HAKIMI",
                R.drawable.hakimi
            ),
            clubs(
                R.drawable.whitecaps,
                R.drawable.bayern,
                0,
                0,
                0,
                0,
                "DAVIES",
                R.drawable.davies
            ),
            clubs(
                R.drawable.groningen,
                R.drawable.celtic,
                R.drawable.southampton,
                R.drawable.lvp,
                0,
                0,
                "VAN DJIK",
                R.drawable.vandjik
            ),
            clubs(
                R.drawable.psv,
                R.drawable.mutd,
                R.drawable.lyon,
                R.drawable.fcb,
                0,
                0,
                "DEPAY",
                R.drawable.depay
            ),
            clubs(
                R.drawable.dinamozagreb,
                R.drawable.tottenham,
                R.drawable.rm,
               0,
                0,
                0,
                "MODRIC",
                R.drawable.modric
            ),
            clubs(
                R.drawable.austriaviena,
                R.drawable.bayern,
                R.drawable.hoffeinheim,
                R.drawable.bayern,
                R.drawable.rm,
                0,
                "ALABA",
                R.drawable.alaba
            ),
            clubs(
                R.drawable.gladbach,
                R.drawable.fcb,
                0,
                0,
                0,
                0,
                "TER STEGEN",
                R.drawable.ter
            )

        )

        return guessplayer.asSequence().shuffled().take(10).toList()
    }
}